-- Threads analytics database schema
-- Run this file in the Supabase SQL Editor as the postgres role.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.threads_posts (
  id uuid primary key default gen_random_uuid(),
  threads_post_id text not null unique,
  chain_id uuid,
  parent_post_id uuid references public.threads_posts(id) on delete set null,
  post_kind text not null default 'single'
    check (post_kind in ('single', 'parent', 'reply_1', 'reply_2', 'final_reply')),
  body text not null,
  published_at timestamptz not null,
  permalink text,
  username text,
  media_type text not null default 'TEXT',
  posting_mode text not null default 'legacy'
    check (posting_mode in ('legacy', 'chain')),
  time_slot text
    check (time_slot is null or time_slot in ('morning', 'lunch', 'evening')),
  topic text,
  audience_situation text,
  hook_type text,
  cut_type text,
  psychology_type text,
  cta_type text,
  tone_tags text[] not null default '{}',
  hypothesis text,
  variable_changed text,
  expected_outcome text,
  quality_score numeric(4, 2)
    check (quality_score is null or quality_score between 0 and 10),
  skill_version text,
  generation_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists threads_posts_published_at_idx
  on public.threads_posts (published_at desc);
create index if not exists threads_posts_chain_id_idx
  on public.threads_posts (chain_id);
create index if not exists threads_posts_pattern_idx
  on public.threads_posts (hook_type, cut_type, cta_type);

drop trigger if exists threads_posts_set_updated_at on public.threads_posts;
create trigger threads_posts_set_updated_at
before update on public.threads_posts
for each row execute function public.set_updated_at();

create table if not exists public.threads_metric_snapshots (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.threads_posts(id) on delete cascade,
  collected_at timestamptz not null default now(),
  measurement_window text not null
    check (measurement_window in ('initial', '1h', '6h', '24h', '72h', '7d', 'latest')),
  views bigint not null default 0 check (views >= 0),
  likes bigint not null default 0 check (likes >= 0),
  replies bigint not null default 0 check (replies >= 0),
  reposts bigint not null default 0 check (reposts >= 0),
  quotes bigint not null default 0 check (quotes >= 0),
  shares bigint not null default 0 check (shares >= 0),
  raw_response jsonb not null default '{}'::jsonb,
  unique (post_id, measurement_window)
);

create index if not exists threads_metric_snapshots_post_time_idx
  on public.threads_metric_snapshots (post_id, collected_at desc);
create index if not exists threads_metric_snapshots_views_idx
  on public.threads_metric_snapshots (views desc);

create table if not exists public.threads_hypotheses (
  id uuid primary key default gen_random_uuid(),
  post_id uuid references public.threads_posts(id) on delete cascade,
  hypothesis_text text not null,
  variable_changed text not null,
  target_metric text not null,
  predicted_direction text not null
    check (predicted_direction in ('up', 'down', 'maintain')),
  expected_outcome text,
  status text not null default 'pending'
    check (status in ('pending', 'supported', 'rejected', 'inconclusive')),
  result_summary text,
  confidence numeric(5, 4)
    check (confidence is null or confidence between 0 and 1),
  evaluated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists threads_hypotheses_set_updated_at on public.threads_hypotheses;
create trigger threads_hypotheses_set_updated_at
before update on public.threads_hypotheses
for each row execute function public.set_updated_at();

create table if not exists public.threads_experiments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  variable_tested text not null,
  control_post_id uuid references public.threads_posts(id) on delete set null,
  variant_post_id uuid references public.threads_posts(id) on delete set null,
  target_metric text not null,
  status text not null default 'running'
    check (status in ('planned', 'running', 'completed', 'cancelled')),
  winner text check (winner is null or winner in ('control', 'variant', 'draw', 'inconclusive')),
  result_summary text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists threads_experiments_set_updated_at on public.threads_experiments;
create trigger threads_experiments_set_updated_at
before update on public.threads_experiments
for each row execute function public.set_updated_at();

create table if not exists public.threads_knowledge (
  id uuid primary key default gen_random_uuid(),
  category text not null
    check (category in ('topic', 'hook', 'cut', 'psychology', 'tone', 'readability', 'cta', 'timing', 'other')),
  rule_text text not null,
  evidence_summary text not null,
  evidence_post_ids uuid[] not null default '{}',
  sample_size integer not null default 0 check (sample_size >= 0),
  confidence numeric(5, 4) not null default 0
    check (confidence between 0 and 1),
  status text not null default 'candidate'
    check (status in ('candidate', 'active', 'rejected', 'archived')),
  applicable_conditions jsonb not null default '{}'::jsonb,
  first_observed_at timestamptz not null default now(),
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists threads_knowledge_status_idx
  on public.threads_knowledge (status, category, confidence desc);

drop trigger if exists threads_knowledge_set_updated_at on public.threads_knowledge;
create trigger threads_knowledge_set_updated_at
before update on public.threads_knowledge
for each row execute function public.set_updated_at();

create table if not exists public.threads_analysis_runs (
  id uuid primary key default gen_random_uuid(),
  analysis_type text not null
    check (analysis_type in ('daily', 'weekly', 'experiment', 'manual')),
  period_start timestamptz not null,
  period_end timestamptz not null,
  posts_analyzed integer not null default 0 check (posts_analyzed >= 0),
  summary text not null,
  facts jsonb not null default '[]'::jsonb,
  problems jsonb not null default '[]'::jsonb,
  hypotheses jsonb not null default '[]'::jsonb,
  next_tests jsonb not null default '[]'::jsonb,
  model_name text,
  prompt_version text,
  created_at timestamptz not null default now(),
  check (period_end >= period_start)
);

create or replace view public.threads_post_performance
with (security_invoker = true)
as
select
  p.id,
  p.threads_post_id,
  p.chain_id,
  p.post_kind,
  p.body,
  p.published_at,
  p.permalink,
  p.posting_mode,
  p.time_slot,
  p.topic,
  p.hook_type,
  p.cut_type,
  p.psychology_type,
  p.cta_type,
  p.hypothesis,
  p.variable_changed,
  p.quality_score,
  m.collected_at,
  m.measurement_window,
  coalesce(m.views, 0) as views,
  coalesce(m.likes, 0) as likes,
  coalesce(m.replies, 0) as replies,
  coalesce(m.reposts, 0) as reposts,
  coalesce(m.quotes, 0) as quotes,
  coalesce(m.shares, 0) as shares,
  coalesce(m.likes, 0)
    + coalesce(m.replies, 0)
    + coalesce(m.reposts, 0)
    + coalesce(m.quotes, 0)
    + coalesce(m.shares, 0) as total_engagements,
  case
    when coalesce(m.views, 0) = 0 then 0
    else round(
      100.0 * (
        coalesce(m.likes, 0)
        + coalesce(m.replies, 0)
        + coalesce(m.reposts, 0)
        + coalesce(m.quotes, 0)
        + coalesce(m.shares, 0)
      ) / m.views,
      4
    )
  end as engagement_rate_percent
from public.threads_posts p
left join lateral (
  select s.*
  from public.threads_metric_snapshots s
  where s.post_id = p.id
  order by s.collected_at desc
  limit 1
) m on true;

alter table public.threads_posts enable row level security;
alter table public.threads_metric_snapshots enable row level security;
alter table public.threads_hypotheses enable row level security;
alter table public.threads_experiments enable row level security;
alter table public.threads_knowledge enable row level security;
alter table public.threads_analysis_runs enable row level security;

revoke all on table public.threads_posts from anon, authenticated;
revoke all on table public.threads_metric_snapshots from anon, authenticated;
revoke all on table public.threads_hypotheses from anon, authenticated;
revoke all on table public.threads_experiments from anon, authenticated;
revoke all on table public.threads_knowledge from anon, authenticated;
revoke all on table public.threads_analysis_runs from anon, authenticated;
revoke all on table public.threads_post_performance from anon, authenticated;

grant all on table public.threads_posts to service_role;
grant all on table public.threads_metric_snapshots to service_role;
grant all on table public.threads_hypotheses to service_role;
grant all on table public.threads_experiments to service_role;
grant all on table public.threads_knowledge to service_role;
grant all on table public.threads_analysis_runs to service_role;
grant select on table public.threads_post_performance to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.threads_posts is 'Threads posts and generation attributes.';
comment on table public.threads_metric_snapshots is 'Cumulative Threads Insights captured over time.';
comment on table public.threads_knowledge is 'Evidence-backed reusable rules for future post generation.';
